# Generated by Django 4.1.4 on 2022-12-11 17:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='SOME STRING', max_length=50)),
                ('last_name', models.CharField(default='SOME STRING', max_length=50)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('Choose not to say', 'CHOOSE NOT TO SAY'), ('Others', 'OTHERS'), ('Select Gender', 'SELECT GENDER')], default='Select Gender', max_length=30)),
                ('image', models.ImageField(default='profile.jpg', upload_to='profile_pictures')),
                ('contact_number', models.CharField(default='00000000000', max_length=100)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
