# Generated by Django 4.1.4 on 2022-12-09 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 9, 7, 59, 9, 68059)),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('Choose not to say', 'CHOOSE NOT TO SAY'), ('Others', 'OTHERS'), ('Select Gender', 'SELECT GENDER')], default='Select Gender', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 9, 7, 59, 9, 68059)),
        ),
    ]
