# Generated by Django 4.1.4 on 2022-12-09 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_created_on_profile_first_name_profile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 9, 9, 52, 0, 52775), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 9, 9, 52, 0, 52775), null=True),
        ),
    ]
